#!/usr/bin/env python

Import("env")
Import("env_modules")

env_tick_synchronizer = env_modules.Clone()
module_obj = []

# Godot module registration glue remains at the module root by convention.
env_tick_synchronizer.add_source_files(module_obj, "*.cpp")

# Public Godot-facing classes.
env_tick_synchronizer.add_source_files(module_obj, "src/public/*.cpp")

# Internal protocol codecs and handshake logic.
env_tick_synchronizer.add_source_files(module_obj, "src/protocol/*.cpp")

env.modules_sources += module_obj
